### PR TITLE
support for submodules

### PR DESCRIPTION
**Pull request by grzn**
Hi,

Your recipe is great, but its missing the functionality of recursively cloning and updating submodules.
I added this functionality, that only works if the configuration directive 'recursive' is set to True

### CODE REVIEW

**Comment by zerok** [comment]
Thank you :-) I will look it through ASAP and include it hopefully in the next and probably final release of this recipe. I no longer use buildout so I don't feel qualified to maintain this any longer :-) Besides, there are some more generic approaches for handling checkouts so that this recipe is probably obsolete anyway.

**Comment by zerok** [comment]
Could you perhaps also provide a test-case?

**Comment by grzn** [comment]
Sure,

I'll update the pull request once I have it.

> ---
> 
>   zerok 
> mailto:reply@reply.github.com
> June 26, 2011 10:44 PM
> 
> Could you perhaps also provide a test-case?

**Comment by grzn** [comment]
Hi,

Is there an update on the pull request?

**Comment by zerok** [comment]
Sorry, totally missed your update :-) I will try to find some time for it tonight.

**Comment by zerok** [comment]
Pushed. Thank you :-) I will probably push this out as 0.6.0 and as the final release on Wednesday (historically, I want to wait a day or so in case I messed something up horribly ;-)).

**Comment by grzn** [comment]
Sounds good to me :)
Thanks

**Pull request merged**
