### PR TITLE
add support for Python 3

### PR DESCRIPTION
**Pull request by marcinn**
Here is small patch for Python 3 support. I know that project is abadoned, but I think that community need this. Please accept this patch and release new version to PyPi, or add me as a maintainer of https://pypi.python.org/pypi/zerokspot.recipe.git/  (my account is `marcinn` on PyPi).

### CODE REVIEW

**Comment by zerok** [comment]
Hi :-) Thanks for the patch! I'll try to look into this this weekend or on Monday.

**Comment by marcinn** [comment]
Thanks! :)

**Comment by zerok** [comment]
@marcinn What's the reason for you using this plugin instead of something like mr.developer? I've heard from other people that that's what they use nowadays hence I'm a bit reluctant with regards to the future of zerokspot.gitrecipe.

**Comment by marcinn** [comment]
Well.. I'm using gitrcipe for years. It's good for me and do right its job. 
I don't know mr developer. It looks overfeatured for me. I'm using mostly eggs and few git repos.

**Comment by zerok** [comment]
Hmm... sadly I can only make one real recommendation here then: That you use your fork, give it its own name and release it on PyPI. 

There are a couple of reasons why I can't really do another release of this myself nor simply give you publishing rights:
- I don't use buildout anymore nor have a I any plans to do so again. Because of this, I would be a really bad maintainer here as I wouldn't use this extension myself.
- The naming of this package is rather unfortunate as it contains the name of my personal domain and is therefore directly linked to me as a person. Namespacing sadly didn't work in our favour here :disappointed:  If it had a generic name I'd have given you the respective rights quite easily, but so it's not an option for me.

Sorry, but I hope you can understand my reasons :cry:

**Comment by marcinn** [comment]
I think I understand but I'm sad.

**Pull request closed without merging**
