### PR TITLE
Respect the buildout verbosity level

### PR DESCRIPTION
**Pull request by markvl**
I thought it would be nice if the recipe would respect the verbosity level of the buildout. In other words: only report whether we're pulling updates or that pulling is disabled if the verbosity level is raised.

Alternatively, I'd really appreciate the recipe to at least be silent if the verbosity level is decreased. (Which can be accomplished by changing ">" in line 118 to ">=".)

Thanks,
Mark

### CODE REVIEW

**Comment by zerok** [comment]
Sounds got to me. I'll look into it tomorrow evening :-)

**Comment by zerok** [comment]
Or earlier. Building a release now. Should be up in a few minutes. Thank you :-)

**Comment by markvl** [comment]
Thanks for the quick response! 
However... it could be me, but I've got the feeling the released egg on PyPI is broken. If I try to use it, it complains about a missing README.rst. As far as I can see the file is indeed not in the tarball while it is being referenced in the setup.py.

**Comment by zerok** [comment]
Which just proves again that doing anything other than reading is just a stupid idea. Will fix it ASAP.

**Comment by zerok** [comment]
Should be fixed now (in the 3rd attempt) :-)

**Comment by markvl** [comment]
Works like a charm, thanks!

**Pull request merged**
